# Base configs
baseurl: "photography.nicholasaborrelli.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Balling Photography"
subtitle: "Photographer for the Penn State Paintball Club Team"
author: "Nicholas Borrelli"
header:
 title: "Photography"
 subtitle: "by Nicholas Borrelli"
footer:
 name: "Hey there, my name is Nick"
 bio: "CHANGE"
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork this project on github</a> ;)"
web_design: "AJ"
social_urls:
  #facebook: "https://www.facebook.com/CHANGE"
  #twitter: "https://www.twitter.com/CHANGE"
  #instagram: "https://www.instagram.com/CHANGE"
  #linkedin: "https://in.linkedin.com/in/CHANGE"
  #github: "https://www.github.com/CHANGE"
